version: '2'
services:
  owncloud:
    restart: on-failure:4
    image: "owncloud:9.0.2-apache"
    ports:
    - "80"
    volumes:
    - owncloud_data:/var/lib/mysql
volumes:
  owncloud_data:
    driver: local
